<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends EntityRepository
{
    public function findAllAccepted()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Registro r Where r.aceptado = TRUE ORDER BY r.paterno ASC'
            )
            ->getResult();
    }

}
